import unittest
from src.summary.post.post_summary import PostSummary
from src.summary.post import post_summary


class MyTestCase(unittest.TestCase):
    def test_mutate_dict(self):
        args_input = lambda x: int(x)
        dict_input = {'กรณี': 10, 'ค่า': 8}
        dict_expect = {'กรณี': {'text': 'กรณี', 'value': 10}, 'ค่า': {'text': 'ค่า', 'value': 8}}
        self.assertEqual(post_summary.mutate_dict(args_input, dict_input), dict_expect)

    def test_generateWordCloud(self):
        input = {'post': {'emotions': "{'ถูกใจ': '0'}{'ขำกลิ้ง': '0'}{'หลงรัก': '0'}{'ซึ้ง': '0'}{'สยอง': '0'}{'ทึ่ง': '0'}", 'id': '39052854', 'post_date': '07/14/2019 05:33:40', 'post_story': 'คือไปเปิด settrade นั่งดู งบการเงิน ไปเรื่อยๆ ครับ \n\nบางทีสังเกตุว่า หุ้นบางตัวในงบการเงิน ของ settrade มันจะไม่ขึ้นค่า P/BV \n\nก็เลยสงสัยว่า ทำไมหุ้นบางตัวมันคำนวน ค่า P/BV ไม่ได้\n\nเป็นเพราะมันถูก SP มานานหรือเปล่า หรือมีเหตุผลเป็นอย่างอื่น ครับ', 'post_tags': 'Value Investment,Fundamental Analysis', 'post_title': 'ทำไมหุ้นบางตัวไม่มีค่า P/BV เช่น BLISS', 'total_comment': 3, 'user_id': 'Nokia3310'}, 'comments': [{'content': 'p/bv\nprice/book value\nหาเองโดยไปดูราคาตลาด (market cap)หารด้วยส่วนของผู้ถือหุ้น\nmarket cap ไม่มีบอก ก็ไปดูจำนวนหุ้นทั้งหมด คูณราคาปัจจุบัน\nแต่ตัวนี้ ไปหาแล้ว ไม่เจอจำนวนหุ้นทั้งหมดเหมือนกันแฮะ\n\nเหมาะแล้วที่เป็นหุ้น sp ฮาาาาา\nแก้ไขข้อความเมื่อ 14 กรกฎาคม เวลา 06:28 น.', 'id': '39052854_07_14_2019_06:27:51', 'post_date': '07/14/2019 06:27:51', 'user_id': 'สมาชิกหมายเลข 4563750', 'status': 'old', 'result': 0}, {'content': 'หาเองได้ครับ แต่ที่ไม่แสดงค่าน่าจะมาจากการถูก SP มานาน...ข้อมูลอาจจะไม่ต่อเนื่อง\n\nไปดูที่งบการเงิน Q119\n\nจำนวนหุ้นอยู่ที่ 6,875,204,000 หุ้น*ราคาล่าสุด 0.15 ดังนั้น MKT CAP อยู่ที่ 1,031,280,600 บาท ดูในงบจะเห็นส่วนของผู้ถือหุ้นหรือ BV อยู่ที่ 1,653,140,000.-บาท ดังนั้น P/BV = 1031280600/1653140000 = 0.6238 เท่า', 'id': '39052854_07_14_2019_11:01:58', 'post_date': '07/14/2019 11:01:58', 'user_id': 'Phunmet', 'status': 'old', 'result': 0}, {'content': 'ระวัง book value ที่มันไม่ value นะครับ', 'id': '39052854_07_15_2019_12:00:48', 'post_date': '07/15/2019 12:00:48', 'user_id': 'นักธุรกิจรายย่อย', 'status': 'old', 'result': 0}]}
        expected = {'pbv': {'text': 'pbv', 'value': 4}, 'ใน': {'text': 'ใน', 'value': 70}, 'pricebookvalue': {'text': 'pricebookvalue', 'value': 5}, 'หา': {'text': 'หา', 'value': 49}, 'เอง': {'text': 'เอง', 'value': 63}, 'โดย': {'text': 'โดย', 'value': 69}, 'ไปด้': {'text': 'ไปด้', 'value': 73}, 'ราคาตลาด': {'text': 'ราคาตลาด', 'value': 44}, 'marketcap': {'text': 'marketcap', 'value': 2}, 'หาร': {'text': 'หาร', 'value': 50}, 'ด้วย': {'text': 'ด้วย', 'value': 23}, 'ส่วน': {'text': 'ส่วน', 'value': 47}, 'ของ': {'text': 'ของ', 'value': 11}, 'ผู้ถือหุ้น': {'text': 'ผู้ถือหุ้น', 'value': 39}, 'ไม่': {'text': 'ไม่', 'value': 74}, 'บอก': {'text': 'บอก', 'value': 35}, 'ก็': {'text': 'ก็', 'value': 10}, 'จำนวน': {'text': 'จำนวน', 'value': 20}, 'หุ้น': {'text': 'หุ้น', 'value': 52}, 'ทั้งหมด': {'text': 'ทั้งหมด', 'value': 27}, 'คูณ': {'text': 'คูณ', 'value': 16}, 'ราคา': {'text': 'ราคา', 'value': 43}, 'ปัจจุบัน': {'text': 'ปัจจุบัน', 'value': 37}, 'แต่': {'text': 'แต่', 'value': 66}, 'ตัว': {'text': 'ตัว', 'value': 24}, 'นี้': {'text': 'นี้', 'value': 33}, 'ไป': {'text': 'ไป', 'value': 72}, 'แล้ว': {'text': 'แล้ว', 'value': 67}, 'เจอ': {'text': 'เจอ', 'value': 56}, 'เหมือนกับ': {'text': 'เหมือนกับ', 'value': 61}, 'แฮะ': {'text': 'แฮะ', 'value': 68}, 'เหมาะ': {'text': 'เหมาะ', 'value': 60}, 'ที่': {'text': 'ที่', 'value': 28}, 'เป็น': {'text': 'เป็น', 'value': 57}, 'ฮา': {'text': 'ฮา', 'value': 55}, 'หาาา': {'text': 'หาาา', 'value': 51}, 'แก้ไข': {'text': 'แก้ไข', 'value': 64}, 'ข้อความ': {'text': 'ข้อความ', 'value': 12}, 'เมื่อ': {'text': 'เมื่อ', 'value': 58}, 'กรกฎาคม': {'text': 'กรกฎาคม', 'value': 7}, 'เวลา': {'text': 'เวลา', 'value': 59}, 'ได้': {'text': 'ได้', 'value': 71}, 'ครับ': {'text': 'ครับ', 'value': 14}, 'แข็งค่า': {'text': 'แข็งค่า', 'value': 65}, 'น่า': {'text': 'น่า', 'value': 34}, 'จาก': {'text': 'จาก', 'value': 19}, 'การ': {'text': 'การ', 'value': 8}, 'ถูก': {'text': 'ถูก', 'value': 26}, 'มา': {'text': 'มา', 'value': 41}, 'นาน': {'text': 'นาน', 'value': 32}, 'ข้อมูล': {'text': 'ข้อมูล', 'value': 13}, 'อาจ': {'text': 'อาจ', 'value': 54}, 'ต่อเนื่อง': {'text': 'ต่อเนื่อง', 'value': 25}, 'การเงิน': {'text': 'การเงิน', 'value': 9}, 'อยู่': {'text': 'อยู่', 'value': 53}, '7': {'text': '7', 'value': 0}, 'ผุ้': {'text': 'ผุ้', 'value': 38}, 'นรา': {'text': 'นรา', 'value': 30}, 'คา': {'text': 'คา', 'value': 15}, 'ล่า': {'text': 'ล่า', 'value': 45}, 'สุ': {'text': 'สุ', 'value': 46}, 'ดังนั้น': {'text': 'ดังนั้น', 'value': 21}, 'mktcap': {'text': 'mktcap', 'value': 3}, 'บาท': {'text': 'บาท', 'value': 36}, 'ดู': {'text': 'ดู', 'value': 22}, 'งบ': {'text': 'งบ', 'value': 17}, 'จะ': {'text': 'จะ', 'value': 18}, 'เห็น': {'text': 'เห็น', 'value': 62}, 'หรือ': {'text': 'หรือ', 'value': 48}, 'ท่า': {'text': 'ท่า', 'value': 29}, 'ระวัง': {'text': 'ระวัง', 'value': 42}, 'bookvalue': {'text': 'bookvalue', 'value': 1}, 'มัน': {'text': 'มัน', 'value': 40}, 'value': {'text': 'value', 'value': 6}, 'นะ': {'text': 'นะ', 'value': 31}}
        self.assertEqual(PostSummary(input).generateWordCloud(), expected)


if __name__ == '__main__':
    unittest.main()
