export const LOAD_RETRIEVED_POST_DATA = 'LOAD_RETRIEVED_POST_DATA';
export const LOAD_RETRIEVED_COMMENT_DATA = 'LOAD_RETRIEVED_COMMENT_DATA';
export const LOAD_STATISTIC_DATA = 'LOAD_STATISTIC_DATA';
export const LOAD_STATISTIC_IMAGE = 'LOAD_STATISTIC_IMAGE';
export const LOAD_MODEL_COMMENT = 'LOAD_MODEL_COMMENT';
export const LOAD_MODEL_COMMENT_SINGLE = 'LOAD_MODEL_COMMENT_SINGLE';
export const ASSIGN_LOGIN = 'ASSIGN_LOGIN';
export const ASSIGN_LOGOUT = 'ASSIGN_LOGOUT';
export const LOAD_PENDING_COMMENT_DATA = 'LOAD_PENDING_COMMENT_DATA';
export const LOAD_SAVED_DATA = 'LOAD_SAVED_DATA';
export const LOAD_POST_SUMMARY_DATA = 'LOAD_POST_SUMMARY_DATA';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const SAVE_COMMENT_RESULT = 'SAVE_COMMENT_RESULT';

// Global Scene
export const OPEN_ALERT = 'OPEN_ALERT';
export const CLOSE_ALERT = 'CLOSE_ALERT';
export const OPEN_CONFIRM_LOGOUT = 'OPEN_CONFIRM_LOGOUT';
export const CLOSE_CONFIRM_LOGOUT = 'CLOSE_CONFIRM_LOGOUT';
export const OPEN_CONFIRM_SAVE_MODAL = 'OPEN_CONFIRM_SAVE_MODAL';
export const CLOSE_CONFIRM_SAVE_MODAL = 'CLOSE_CONFIRM_SAVE_MODAL';
export const TOGGLE_NAV_SIDE = 'TOGGLE_NAV_SIDE';
export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';

// Spinner
export const OPEN_SPINNER = 'OPEN_SPINNER';
export const CLOSE_SPINNER = 'CLOSE_SPINNER';
